### ISSUE TITLE
Replace rules no longer working with regex

### ISSUE THREAD

**Issue by rogeramitchell** [requestly/rules#2]
Thank you for developing this extension, it has been a great timesaver!

I noticed an issue with the most recent extension release (v4.2.12).

As described in [this blog post](https://medium.com/@RogerMitchell/using-requestly-in-visualforce-development-workflow-dd64e5f5998f), I am using replace rules with regex to direct to localhost.

It appears that the most recent version does not replace the host as expected. Note that this issue did not exist in the prior minor release (v4.2.11).

> This site can’t be reached
> c.cs62.visualforce.com’s server DNS address could not be found.
> Try running Network Diagnostics.
> DNS_PROBE_FINISHED_NXDOMAIN

Did something change w.r.t how replace rules are handling regex?

**Comment by sachinjain024** [comment]
@rogeramitchell As I told you in another ticket, there is hardly change in v4.2.11 to v4.2.13. I just enabled requestly extension code to run on

    requestly.github.io // v4.2.12
    www.requestly.in // v4.2.13

Apart from that there is no change. It looks like there is a problem with DNS of visualforce.com itself. Try pinging `c.cs62.visualforce.com` and do nslookup `c.cs62.visualforce.com` in command line.

Please note `cs62.visualforce.com` is working fine. It's just newly `c.` is not resolved. You should talk to your DNS provider about getting this fixed.

**Comment by rogeramitchell** [comment]
I tweaked the regex that I used in my replace rule and it now works. The same URLs in prior versions matched the regex defined in the blog post; was there an update to how the regex works?

**Comment by sachinjain024** [comment]
@rogeramitchell I am pretty certain that nothing changed w.r.t working of Regex. No release went out recently which could have done this. 

Is it possible that the URL on which your regex was working got changed by a bit due to which you have to tweak your regex as well ? I am just making a wild guess here.

If you could tell me your regex and your URL, I can probably think why your previous regex stopped working.

**Comment by rogeramitchell** [comment]
@sachinjain024 here's the original regex that I was using, along with the URL that I tested
```
https://rm-df15-dev-ed--c.na34.visual.force.com/resource/1485117744000/Name_of_Directory/
/https.*\/resource(\/[0-9]+)?/Name_of_Directory/ig
```

Here's the regex that I am currently using, which works with the base URL above `c.cs62.visualforce.com`
```
/https.*\/resource\/[0-9]+\/Name_of_Directory/ig
```

**Comment by sachinjain024** [comment]
@rogeramitchell There is an issue in your previous regex. There is an unescaped "slash (/)" before Name_of_Directory

    /https.*\/resource(\/[0-9]+)?    "/"      Name_of_Directory/ig

Note the above slash in quotes is not escaped in the regex and that's why probably your regex was not working. Try the following

    /https.*\/resource(\/[0-9]+)?\/Name_of_Directory/ig

## How I found your error
1. Go to regex101.com
2. Select Javascript from left column
3. Enter your regex
4. Enter your test string

Here is an example I created for you: https://regex101.com/r/ChAOyF/2

**Comment by rogeramitchell** [comment]
Makes sense, not sure how that worked for any part of the app. Thanks for your review, and for creating such an awesome extension!

**Comment by sachinjain024** [comment]
@rogeramitchell Thanks for turn around. Can you please rate us on Chrome Store: https://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa ?
